org: pithesh
app: product-service
service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors: true


plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  autoswagger:
    typefiles: ['./src/types/product.types.ts', './src/types/api.types.ts']
  serverless-offline:
    noPrependStageInUrl: true

functions:
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
  getProductsList :
    handler: handler.getProductsList 
    events:
      - http:
          path: products
          method: get
          cors: true