org: pithesh
service: import-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
             - "s3:GetObject"
             - "s3:PutObject"
             - "s3:DeleteObject"
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-esbuild

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  autoswagger:
    typefiles: ['./src/types/api.types.ts']
  serverless-offline:
    noPrependStageInUrl: true
  dotenv:
    path: .env
  esbuild:
    platform: node
    target: node18  
  bucket: ${env:BUCKET}
    

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
    environment:
        BUCKET: ${self:custom.bucket}
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true